// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const findByID = `-- name: FindByID :one
SELECT user_id, email, first_name, last_name FROM users WHERE user_id = $1
`

func (q *Queries) FindByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}
